In [130]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

train_raw = pd.read_csv('../data/train.csv')
test_set = pd.read_csv('../data/test.csv')

train_features = train_raw.iloc[:,2:]
train_target = LabelEncoder().fit(train_raw.iloc[:,1]).transform(train_raw.iloc[:,1])
train_target = pd.Series(train_target)
test_set = test_set.iloc[:,1:]

print("train_features's shape is {} and its head is \n{}".format(train_features.shape, train_features.head()))
#print("train_target's shape is {} and its head is \n{}".format(train_target.shape, train_target.head()))
print("test_set's shape is {} and its head is \n{}".format(test_set.shape, test_set.head()))
train_target

train_features's shape is (990, 192) and its head is
    margin1   margin2   margin3   margin4   margin5   margin6   margin7  \
0  0.007812  0.023438  0.023438  0.003906  0.011719  0.009766  0.027344
1  0.005859  0.000000  0.031250  0.015625  0.025391  0.001953  0.019531
2  0.005859  0.009766  0.019531  0.007812  0.003906  0.005859  0.068359
3  0.000000  0.003906  0.023438  0.005859  0.021484  0.019531  0.023438
4  0.005859  0.003906  0.048828  0.009766  0.013672  0.015625  0.005859

   margin8   margin9  margin10    ...      texture55  texture56  texture57  \
0      0.0  0.001953  0.033203    ...       0.007812   0.000000   0.002930
1      0.0  0.000000  0.007812    ...       0.000977   0.000000   0.000000
2      0.0  0.000000  0.044922    ...       0.154300   0.000000   0.005859
3      0.0  0.013672  0.017578    ...       0.000000   0.000977   0.000000
4      0.0  0.000000  0.005859    ...       0.096680   0.000000   0.021484

   texture58  texture59  texture60  texture61  texture62  texture63  texture64
0   0.002930   0.035156        0.0        0.0   0.004883   0.000000   0.025391
1   0.000977   0.023438        0.0        0.0   0.000977   0.039062   0.022461
2   0.000977   0.007812        0.0        0.0   0.000000   0.020508   0.002930
3   0.000000   0.020508        0.0        0.0   0.017578   0.000000   0.047852
4   0.000000   0.000000        0.0        0.0   0.000000   0.000000   0.031250

[5 rows x 192 columns]
test_set's shape is (594, 192) and its head is
    margin1   margin2   margin3   margin4   margin5   margin6   margin7  \
0  0.019531  0.009766  0.078125  0.011719  0.003906  0.015625  0.005859
1  0.007812  0.005859  0.064453  0.009766  0.003906  0.013672  0.007812
2  0.000000  0.000000  0.001953  0.021484  0.041016  0.000000  0.023438
3  0.000000  0.000000  0.009766  0.011719  0.017578  0.000000  0.003906
4  0.001953  0.000000  0.015625  0.009766  0.039062  0.000000  0.009766

   margin8   margin9  margin10    ...      texture55  texture56  texture57  \
0      0.0  0.005859  0.023438    ...       0.006836   0.000000   0.015625
1      0.0  0.033203  0.023438    ...       0.000000   0.000000   0.006836
2      0.0  0.011719  0.005859    ...       0.128910   0.000000   0.000977
3      0.0  0.003906  0.001953    ...       0.012695   0.015625   0.002930
4      0.0  0.005859  0.000000    ...       0.000000   0.042969   0.016602

   texture58  texture59  texture60  texture61  texture62  texture63  texture64
0   0.000977   0.015625        0.0        0.0   0.000000   0.003906   0.053711
1   0.001953   0.013672        0.0        0.0   0.000977   0.037109   0.044922
2   0.000000   0.000000        0.0        0.0   0.015625   0.000000   0.000000
3   0.036133   0.013672        0.0        0.0   0.089844   0.000000   0.008789
4   0.010742   0.041016        0.0        0.0   0.007812   0.009766   0.007812

[5 rows x 192 columns]

0       3
1      49
2      65
3      94
4      84
5      40
6      54
7      78
8      53
9      89
10     98
11     16
12     74
13     50
14     58
15     31
16     43
17      4
18     75
19     44
20     83
21     84
22     13
23     66
24     15
25      6
26     73
27     22
28     73
29     31
       ..
960    85
961    89
962    94
963    45
964    48
965    86
966    81
967    14
968     4
969    77
970    56
971    82
972     2
973    85
974    70
975    88
976     0
977    75
978    14
979    86
980    81
981    97
982    70
983    72
984    34
985    40
986     5
987    11
988    78
989    50
Length: 990, dtype: int64

In [131]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import log_loss


X_train, X_test, y_train, y_test = train_test_split(train_features, train_target, test_size = 0.2, random_state = 123)
from sklearn.svm import SVC
model = SVC(kernel = 'linear', C=1000)
model.fit(X_train, y_train)
predictions = model.predict(X_test)

model.score(X_test, y_test)

0.9242424242424242

In [132]:
print(type(predictions))
y_test = np.array(y_test)

pd.DataFrame(predictions,y_test)

<class 'numpy.ndarray'>

     0
98  98
39  39
41  41
59  59
74  74
87  87
74  74
85  85
65  65
13   7
55  55
48  48
0    0
37  37
21  21
8    8
58  58
42  42
75  75
41  41
53  53
61  61
21  21
39  39
90  90
78  78
41  41
77  77
75  75
22  22
..  ..
43  43
86  86
24  24
35  35
49  49
30  30
32  32
76  76
41  41
22  22
84  84
57  57
92  92
53  53
26   7
92  92
86  86
52  52
58  58
54  54
2    2
93  93
66  66
11  11
5   35
79  79
63  63
37  37
44  44
42  42

[198 rows x 1 columns]